worktree-path = "{{ repo_path }}/{{ branch | sanitize }}"

[post-create]
design = 'ln -sfn {{ repo_path }}/{{ default_branch }}/docs/design {{ worktree_path }}/docs/design'
jj = '[ -d .jj ] || jj git init --git-repo={{ repo_path }}'
