command_timeout = 2000

format = """
[┌─>](bold green) \
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$kubernetes\
$vcsh\
$git_state\
$git_metrics\
$hg_branch\
$python\
$nix_shell\
$conda\
$memory_usage\
$aws\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$battery\
$line_break\
$jobs\
$time\
$status\
$shell\
[└─>](bold green) """

# format = """
# $username\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $python\
# $nix_shell\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $shell"""

[character]
format = "$"

[kubernetes]
disabled = false
format = 'in [$symbol$context]($style) '

[git_status]
#symbol=''
#conflicted = "🚩"
#ahead = "🚀"
#behind = "🐢"
#diverged = "🚧"
#up_to_date = "✓"
#untracked = "🆕"
#stashed = "📦"
#modified = "📝"
#staged = '[++\($count\)](green)'
#renamed = "👅"
#deleted = "🗑"

[aws]
format = 'on [$symbol$profile/$region]($style) '
symbol = "☁ "

[aws.profile_aliases]
prod = "PROD"
